name: COLA
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - notebook
  - imgviz
  - torchaudio
  - cudatoolkit
  - tqdm
  - ipywidgets
  - tensorboard
  - imgaug
  - conda-pack
  - torchinfo
  - clingo
  - flask
  - hydra-core
  - ftfy
  - regex
  - tsnecuda
  - seaborn
  - transformers
  - captum
  - libwebp-base=1.3.2
  - jupyterlab
